[package]
name = "crux-lib"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
const_for = "0.1.5"
